### ISSUE TITLE
bootstrap node access issue

### ISSUE THREAD

**Issue by atlas4it** [Hamza-Mandviwala/OCP4.10.3-install-GCP-UPI#2]
I could not access to bootstrap node. I can't see any step for that.
connectrivity is good 
I could not access neither from bastion nor from my laptop

Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Comment by Hamza-Mandviwala** [comment]
@atlas4it - If you followed the steps per the doc, then you will not be able to ssh directly from your laptop. The ssh session will have to be initiated from the bastion host itself.

The error seen is expected initially when the bootstrap node is being initialized. This initialization process takes some time as the node boots up, installs some necessary packages and also restarts at least once. If you ssh during this time, you might run into the error you are seeing. 

If you are sure all prior steps were executed correctly, then allow some time and then try ssh'ing again. 

Please ensure you are using the correct private key of your bastion host when ssh'ing into the bootstrap node ( e.g `ssh -i ~/.ssh/id_rsa core@<private IP of your bootstrap node>`  , where `~/.ssh/id_rsa` is the private key you created in the keypair creation step 14). 

Also kindly ensure you pasted the contents of the *public* key of your bastion host into the `install-config.yaml` (step 18 - iv). This is important, and often an error point for many (including myself). If this step is executed incorrectly, then all your cluster nodes would have an incorrect public key injected into them, and ssh'ing into them would fail.

P.s Thank you for the feedback , I have added the ssh command in step 35 to avoid confusion. However if you follow the [YouTube video](https://www.youtube.com/watch?v=DdWCL4eE0vM) at the timestamp of 31:00, it does demonstrate the command for ssh'ing into the bootstrap and master nodes.

**Comment by atlas4it** [comment]
this is solved the issue ! the key word is the user : core !

**Comment by Hamza-Mandviwala** [comment]
Thanks for the update. Will close this issue now.
