### ISSUE TITLE
allow access to openshift server api

### ISSUE THREAD

**Issue by atlas4it** [Hamza-Mandviwala/OCP4.10.3-install-GCP-UPI#3]
Now that the cluster is up and all nodes are healthy
I wanted to backup my openshift cluster using dell emc Dell EMC PowerProtect Data Manager installed outside GCP.
So I need to access cluster using API     https://api.openshift.infra.labs:6443

what are the required actions in order to allow access to openshift ?

I wanted also to create a dashboard service account. Could you please help

**Comment by Hamza-Mandviwala** [comment]
@atlas4it - Good to know your cluster is up and healthy! 

If I understand correctly, you wish to backup your OpenShift cluster using Dell EMC PowerProtect Data Manager installed outside of your GCP account, but are unable to do so as the API you are referring to is probably not accessible outside of your GCP network, correct? The cluster installation demonstrated in this exercise is a private cluster, which can only be accessed through the bastion host. So you might not be able to directly access the api externally. However, some ideas I can think of:

1. You might want to leverage GCP's VPN functionality and try extending the gcp network to the network where your Dell EMC PowerProtect Data Manager is hosted. This way you might be able to get direct access to the OpenShift API of your cluster.
2. You can try exploring the option of deploying DDVE on Google Cloud itself in the same vpc and subnet as your OpenShift cluster. Here is the reference link with detailed steps - https://infohub.delltechnologies.com/l/dell-emc-powerprotect-dd-virtual-edition-on-google-cloud/deploying-ddve-on-google-cloud

Regarding the service account creation, it is quite similar to creating a service account in any Kubernetes distribution. You can do so using the `oc` cli binary. Kindly refer https://docs.openshift.com/container-platform/4.7/authentication/understanding-and-creating-service-accounts.html for more information on creating service accounts using the `oc` cli. 

I hope I've understood your asks and answered them to your needs correctly. :)

**Comment by Hamza-Mandviwala** [comment]
Closing this issue.
